'use client';
/* oxlint-disable next/no-img-element -- Exact local native-app artwork is reused at its display size. */
import {useState} from 'react';
import {Activity,Check,Volume2,Lightbulb,LightbulbOff,Info,Radio,Settings,ChevronDown,ChevronUp,CircleHelp,Ellipsis,SlidersHorizontal,Zap,Sparkles} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Popover,PopoverTrigger,PopoverContent} from '@/components/ui/popover';
import {Tooltip,TooltipTrigger,TooltipContent,TooltipProvider} from '@/components/ui/tooltip';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import native from './native-controls.json';
import {presets} from './lighting';
export type DemoControls={volume:number;bass:number;mid:number;treble:number;extra:boolean;light:number;lightOn:boolean;connected:boolean;autoStandby:boolean;btStandby:boolean;codec:'Auto'|'SBC'};
function Help({label,text}:{label:string;text:string}){const [open,setOpen]=useState(false);return <Tooltip open={open} onOpenChange={setOpen}><TooltipTrigger className="icon-button help-button" aria-label={`About ${label}`} onClick={()=>setOpen(!open)}><CircleHelp size={14}/></TooltipTrigger><TooltipContent role="tooltip" className="native-tooltip" side="top"><span><strong>{label}</strong>{text}</span></TooltipContent></Tooltip>}
function Swatch({index}:{index:number}){return <span className={'light-swatch light-swatch-'+index} style={{background:`linear-gradient(135deg,${presets[index].colors.join(',')}${presets[index].colors.length===1?','+presets[index].colors[0]:''})`}}>{index===0?<LightbulbOff size={20}/>:presets[index].strobe?<Zap size={20}/>:index===3?<Sparkles size={20}/>:null}</span>}
export default function WebController({state,set}:{state:DemoControls;set:<K extends keyof DemoControls>(key:K,value:DemoControls[K])=>void}){
 const [eq,setEQ]=useState(false),[palette,setPalette]=useState(false),[about,setAbout]=useState(false),[menu,setMenu]=useState(false);
 const disabled=!state.connected;
 const signed=(n:number)=>n>0?`+${n}`:n;
 return <TooltipProvider delay={300}><div className="native-controller" aria-label="XB30 Controller interactive demo">
 <header className="native-header"><img src="./speaker-native.webp" alt="BinaryBears blue XB30"/><div className="native-heading"><div className="title-line"><h2>XB30 Controller</h2><button className="icon-button" aria-label="About XB30 Controller" title="About this device and app" onClick={()=>setAbout(true)}><Info size={15}/></button></div><div className="connection-line"><button className="native-button" onClick={()=>set('connected',!state.connected)} title="Simulate the speaker control connection. No Bluetooth device is accessed.">{disabled?'Connect':'Disconnect'}</button><span className={'native-status '+(disabled?'disconnected':'')}><Check size={12}/>{disabled?'Disconnected':'Connected'}</span></div><div className="native-volume"><Volume2 size={19}/><Slider aria-label="Volume" value={[state.volume]} min={0} max={100} step={2} disabled={disabled} onValueChange={v=>set('volume',Array.isArray(v)?v[0]:v)}/><span title="Changes the actual demo audio level. The real speaker may limit volume when its battery is low.">{disabled?'—':`${state.volume}%`}</span></div></div></header>
 <div className="native-card native-status-strip"><div className="status-half"><span className="battery-icon" aria-hidden="true"><i style={{width:disabled?'0%':'100%'}}/></span><div><strong>Battery</strong><span>{disabled?'—':'Fully charged'}</span></div></div><div className="status-half"><Radio size={25}/><div><strong>Bluetooth</strong><span>{disabled?'Not connected':`Preference: ${state.codec}`}</span></div></div></div>
 <div className="native-columns"><section className="native-card sound-card"><div className="card-title"><Activity size={21}/><h3>Sound</h3><Help label="Extra Bass & ClearAudio+" text={native.help.sound}/></div><div className="muted preset-label">Sound preset</div><fieldset className="native-segment" aria-label="Sound preset">{[false,true].map(extra=><button key={String(extra)} disabled={disabled} aria-pressed={state.extra===extra} onClick={()=>set('extra',extra)} title={native.help.sound}>{extra?'Extra Bass':'Flat'}</button>)}</fieldset><hr/><div className="eq-summary"><div><strong>Equalizer</strong><span>{disabled?'Bass —   Mid —   Treble —':`Bass ${signed(state.bass)}   Mid ${signed(state.mid)}   Treble ${signed(state.treble)}`}</span></div><button className="native-button" aria-label={eq?'Close EQ':'Open EQ'} aria-expanded={eq} aria-controls="demo-eq" title="Show or hide the equalizer without changing its values." onClick={()=>setEQ(!eq)}>{eq?<ChevronUp size={14}/>:<ChevronDown size={14}/>}</button></div></section>
 <div className="native-right"><section className="native-card lighting-card"><div className="card-title"><Lightbulb size={21}/><h3>Lighting</h3><Switch aria-label="Lighting" title="Turn speaker illumination on or off. Your last selected effect is kept." disabled={disabled} checked={state.lightOn} onCheckedChange={v=>set('lightOn',v)}/></div><Popover open={palette} onOpenChange={setPalette}><PopoverTrigger className="lighting-selector" disabled={disabled} aria-label={`Choose lighting effect: ${state.lightOn?native.lightNames[state.light]:'Light Off'}`}><Swatch index={state.lightOn?state.light:0}/><strong>{state.lightOn?native.lightNames[state.light]:'Light Off'}</strong><ChevronDown size={14}/></PopoverTrigger><PopoverContent className="native-palette" align="end" side="bottom"><h4>Lighting palette</h4><p>Choose a mood. ⚡ indicates flashing lights.</p><div className="palette-grid">{presets.slice(1).map((preset,i)=>{const index=i+1;return <button key={preset.name} aria-pressed={state.light===index} title={preset.description} className={state.light===index?'selected':''} onClick={()=>{set('light',index);set('lightOn',true);setPalette(false)}}><Swatch index={index}/><span>{native.lightNames[index]}{state.light===index&&<Check size={10}/>}</span></button>})}</div></PopoverContent></Popover></section>
 <section className="native-card codec-card"><div className="card-title"><h3>Bluetooth Mode</h3><Help label="Bluetooth audio mode" text={native.help.codec+' In this web demo the selection is simulated; it does not re-encode the audio.'}/></div><fieldset className="native-segment" aria-label="Bluetooth Mode">{(['Auto','SBC'] as const).map(codec=><button key={codec} disabled={disabled} aria-pressed={state.codec===codec} onClick={()=>set('codec',codec)}>{codec}</button>)}</fieldset></section></div></div>
 {eq&&<section id="demo-eq" className="native-card expanded-eq"><div className="card-title"><SlidersHorizontal size={18}/><h3>Equalizer</h3><button className="native-button" onClick={()=>setEQ(false)}>Close</button></div>{(['bass','mid','treble'] as const).map(band=><div className="eq-band" key={band}><label>{band[0].toUpperCase()+band.slice(1)}</label><Slider aria-label={band[0].toUpperCase()+band.slice(1)} disabled={disabled||state.extra} min={-10} max={10} step={1} value={[state[band]]} onValueChange={v=>set(band,Array.isArray(v)?v[0]:v)}/><span>{signed(state[band])}</span></div>)}{state.extra&&<p className="muted">Select Flat to adjust EQ.</p>}</section>}
 <section className="native-card device-card"><div className="card-title"><Settings size={21}/><h3>Device Settings</h3><Popover open={menu} onOpenChange={setMenu}><PopoverTrigger className="icon-button" aria-label="Device menu"><Ellipsis size={18}/><ChevronDown size={11}/></PopoverTrigger><PopoverContent className="native-menu" align="end"><button onClick={()=>{setMenu(false);setAbout(true)}}>About XB30 Controller</button><p>Bluetooth recovery, session logs and Quit are available in the Mac app.</p></PopoverContent></Popover></div><div className="standby-row"><div><label htmlFor="auto-standby">Auto standby</label><Switch id="auto-standby" aria-label="Auto standby" disabled={disabled} checked={state.autoStandby} onCheckedChange={v=>set('autoStandby',v)}/><Help label="Auto standby" text={native.help.autoStandby+' Simulated here; it will not stop the demo.'}/></div><div><label htmlFor="bt-standby">Bluetooth standby</label><Switch id="bt-standby" aria-label="Bluetooth standby" disabled={disabled} checked={state.btStandby} onCheckedChange={v=>set('btStandby',v)}/><Help label="Bluetooth standby" text={native.help.btStandby+' Simulated here; no Bluetooth device is accessed.'}/></div></div></section>
 </div><Dialog open={about} onOpenChange={setAbout}><DialogContent className="native-about"><img src="./binarybears-mark.webp" alt="BinaryBears bear logo"/><DialogTitle>XB30 Controller</DialogTitle><DialogDescription>from BinaryBears</DialogDescription><a href="https://binarybears.com" target="_blank" rel="noreferrer">binarybears.com ↗</a><dl><div><dt>App version</dt><dd>0.2.3 · web preview</dd></div><div><dt>Device</dt><dd>SRS-XB30 · simulated</dd></div><div><dt>Firmware</dt><dd>1.00 · reference device</dd></div></dl><p>Audio and lighting controls act on this demo. Battery, Bluetooth and device settings are simulated. Extra Bass previews bass emphasis; it does not reproduce Sony’s DSP.</p><p>Independent software. Not affiliated with Sony.</p></DialogContent></Dialog></TooltipProvider>
}
